# Change these first
owner: shimuldn # Your GitHub organization or username, where this repository lives
repo: status-piped # The name of this repository

# runner: [self-hosted]
runs-on: ubuntu-latest

sites:
  - name: Piped - Public
    url: http://piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/jp.png
  - name: Piped API - Public
    url: https://api-piped.shimul.me/trending
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/jp.png
  - name: Piped Proxy - Public
    url: http://proxy-piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/jp.png
    
  - name: Piped US - Public
    url: http://us-piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: Piped US API - Public
    url: https://us-api-piped.shimul.me/trending
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: Piped US Proxy - Public
    url: http://us-proxy-piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
    
  - name: Piped DE - Public
    url: http://de-piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: Piped DE API - Public
    url: https://de-api-piped.shimul.me/trending
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: Piped DE Proxy - Public
    url: http://de-proxy-piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
    
  - name: Piped SA - Public
    url: http://sa-piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/sa.png
  - name: Piped SA API - Public
    url: https://sa-api-piped.shimul.me/trending
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/sa.png
  - name: Piped SA Proxy - Public
    url: http://sa-proxy-piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/sa.png
    
  - name: Piped IN - Public
    url: http://in-piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: Piped In API - Public
    url: https://in-api-piped.shimul.me/trending
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: Piped IN Proxy - Public
    url: http://in-proxy-piped.shimul.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.piped.shimul.me
#   baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: Visit Piped
      href: https://piped.shimul.me
#   introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Is this up?
#   navbar:
#     - title: Status
#       href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO
  theme: night
  metaTags:
    - name: "robots"
      content: "noindex"
user-agent: $OWNER
i18n:
  footer: Thank you.
  
workflowSchedule:
    uptime: "0 1 * * *"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
